# -*- coding: utf-8 -*-
"""Copy of st_helens_quakes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9-5F2gPNEIozKXo5qbtdUhQNOlZ1iOp
"""



"""Where under the volcano do earthquakes happen, and how deep?"""

!pip install py3dep

import numpy as np
import pandas as pd
import plotly.graph_objects as go

LAT0, LON0 = 46.200, -122.189      # approximate summit
HALF_LAT, HALF_LON = 0.10, 0.15    # half-size of the box in degrees
south, north = LAT0 - HALF_LAT, LAT0 + HALF_LAT
west,  east  = LON0 - HALF_LON, LON0 + HALF_LON

url = (
    "https://earthquake.usgs.gov/fdsnws/event/1/query?format=csv"
    "&starttime=2004-01-01&endtime=2026-10-01&eventtype=earthquake"
    f"&minlatitude={south}&maxlatitude={north}"
    f"&minlongitude={west}&maxlongitude={east}"
    "&minmagnitude=1.0&orderby=time"
)
quakes = pd.read_csv(url, parse_dates=["time"])

quakes.head()

import plotly.express as px
px.scatter(quakes, x="longitude", y="latitude", color="depth").show()

px.histogram(quakes, x="depth").show()

per_year = quakes.groupby(quakes["time"].dt.year).size()
px.bar(x=per_year.index, y=per_year.values).show()

quakes = quakes.dropna(subset=["depth"])

import py3dep
dem = py3dep.get_map("DEM", (west, south, east, north), resolution=60,
                     geo_crs="EPSG:4326", crs="EPSG:4326")
dem = dem.sortby("y")

print(dem)

float(dem.min()), float(dem.max())

px.imshow(dem.values, origin="lower").show()

!pip install rasterio

kx = 111.32 * np.cos(np.radians(LAT0))   # km per degree of longitude
ky = 110.95                              # km per degree of latitude

X = (dem.x.values - LON0) * kx
Y = (dem.y.values - LAT0) * ky
Z = dem.values / 1000

qx = (quakes["longitude"] - LON0) * kx
qy = (quakes["latitude"]  - LAT0) * ky
qz = -quakes["depth"]



marker=dict(size=2, color=quakes["time"].dt.year,
            colorscale="Plasma", colorbar=dict(title="Year"))

hover = (
    "Date: " + quakes["time"].dt.strftime("%Y-%m-%d %H:%M") + " UTC<br>"
    + "Magnitude: " + quakes["mag"].astype(str) + "<br>"
    + "Depth: " + quakes["depth"].round(1).astype(str) + " km<br>"
    + quakes["place"].astype(str)
)

dots = go.Scatter3d(
    x=qx, y=qy, z=qz, mode="markers",
    marker=dict(size=3, color="red"),
    text=hover,
    hovertemplate="%{text}<extra></extra>",
    name="Earthquakes",
)

terrain = go.Surface(x=X, y=Y, z=Z, colorscale="Earth",
                     opacity=0.6, showscale=False, name="Terrain")

dots = go.Scatter3d(x=qx, y=qy, z=qz, mode="markers",
                    marker=dict(size=2, color="red"), name="Earthquakes")

fig = go.Figure(data=[terrain, dots])
fig.update_layout(
    title="Earthquakes beneath Mount St. Helens",
    scene=dict(xaxis_title="East (km)", yaxis_title="North (km)",
               zaxis_title="Elevation / depth (km)", aspectmode="data"),
)
fig.show()

